server:
  port: 8443
  ssl:
    enabled: true
    key-store: src/main/resources/grapemarket.p12
    key-store-password: bitc5600
    key-store-type: PKCS12
  servlet:
    context-path: /
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grapemarket?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: grapemarket
    password: bitc5600
    
  jpa:
    open-in-view: false    
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
      
#파일업로드  
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB            
      max-request-size: 20MB
        
  
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true 
      
# 시큐리티 사용자 기본 아이디 비번 디폴트 세팅      
  security:
    user:
      name: test
      password: 1234
    oauth2:
      client:
        registration:
          google: 
            client-id: 539550640102-ttcfqed58f6vjimefs07njhkvb2atmio.apps.googleusercontent.com
            client-secret: mJ_Aoxv9AolJSFIFYMoz7CKL
            scope: 
            - email
            - profile
          

      
#파일 저장할 경로(각자 파일 경로로)
#정민학원컴퓨터경로: C:/Users/it/Documents/GitHub/grapemarket-web/grapemarket/src/main/resources/static/upload/ (지우지마세여;))
file:
  path: C:/Users/it/Documents/GitHub/grapemarket-web/grapemarket/src/main/resources/static/upload/

